The goal of this test suite:
{task}

The actions already executed are the following:
{history}

The test you are now running is the following. Only execute what is required to run this exact test:
{instructions}

You must answer using a properly json output containing in this order:
- your reasoning to pick this action
- if this action is final
- the action you want to execute next and its parameters according to the JSON schema of the action

{format}